import turtle
wn=turtle.Screen()
wn.bgcolor("black")
sam=turtle.Turtle()
sam.setposition(50,300)
sam.speed(0)
sam.color("Red","Blue")
sam.begin_fill()
def square(turtle,size,angle):
    for i in range(3):
        turtle.forward(size)
        turtle.right(angle)
        turtle.forward(size)
for a in range(4):
    square(sam,100,90)
    sam.penup()
    sam.forward(100)
    sam.pendown()
sam.end_fill()
sam.penup()
sam.forward(500)
sam.pendown()
   
#sam.end_fill()
ram=turtle.Turtle()
ram.setposition(0,-200)
ram.color("yellow","green")
ram.speed(0)
ram.begin_fill()
def star(turtle,size,angle):
	for z in range(100):
		turtle.forward(size)
		turtle.left(angle)
		turtle.forward(size)
star(ram,200,175)
ram.end_fill()
ram.penup()
ram.forward(500)
ram.pendown()
vs=turtle.Turtle()
vs.setposition(0,300)
vs.color("red","black")
vs.begin_fill()
for x in range(1):
	vs.forward(150)
	vs.right(90)
	vs.forward(100)
	vs.right(90)
	vs.forward(300)
	vs.right(90)
	vs.forward(100)
	vs.right(90)
	vs.forward(100)
	vs.left(90)
	vs.forward(100)
	vs.right(90)
	vs.forward(100)
	vs.right(90)
	vs.forward(300)
	vs.right(90)
	vs.forward(100)
	vs.right(90)
	vs.forward(200)
	vs.right(90)
	vs.forward(50)
vs.end_fill()
turtle.done()
